### ISSUE TITLE
Can't use colored slimes to craft slime things (leads, etc)

### ISSUE THREAD

**Issue by Rayxanber** [CrimsonFluff/Crimson-Slimes#3]
Fabric Version 0.13.3
Mod Version Crimson-Slimes-1.18.2-Fabric-v1.0.0
Both

**Describe the bug**
Cannot use colored slimeballs for Vanilla recipes or modded

**Comment by CrimsonFluff** [comment]
thats because vanilla/modded recipes need to be changed to support the `crimsonslimes/slime_balls` and `crimsonslimes/slime_blocks` tags - Forge has a default slime tag but Fabric does not

you cant just throw mods together and have everything work.  I could add extra recipes for the vanilla stuffs tho... but its easy enough to add a datapack loader and change recipes - especially as mod packs will most likely change recipes anyways

**Comment by CrimsonFluff** [comment]
not going to do anything
changes can be made with data-packs like all good mod packs, as always is, was and will be

or until Fabric introduces a global slimes tag

**Comment by Skylortrexler** [comment]
Wow dude you're rude as hell. Why didn't you add your slime balls to the tag and include that with your mod?

**Comment by Skylortrexler** [comment]
You can define tags yourself using vanilla data pack stuff...

**Comment by CrimsonFluff** [comment]
fabric does not have a slimeball tag
most people that make modpacks, i would have thought, would make the changes themselves

not trying to be rude

**Comment by CrimsonFluff** [comment]
if you find a fabric mod that also adds slimes, then of course I will look and see how they handle it

I even suggested 2 ways to overcome this issue.  if you really really wanted me to do something you could just ask and put your point across, not cry about it

**Comment by Skylortrexler** [comment]
Dude you just make your own and bundle it with the mod.  
`it means going through every single vanilla recipe and manually changing them`
Oh, like you are asking the users to do? I did it when I added a dozen new tool materials that conflicted with vanilla recipes for my Mod Sentimentality 3. There is even a "replace: false" that you can use to prevent ruining other mods that touch the same recipe. 

It's fine if you don't want to be a modder who cares about making the user experience better, but don't expect to get put in a modpack if you don't work with the users to make it easier.

**Comment by Skylortrexler** [comment]
`if you really really wanted me to do something you could just ask and put your point across, not cry about it`

I wish you good luck in life.

**Comment by CrimsonFluff** [comment]
my thinking is that as there is no common slime ball tag (for fabric) , the mod pack maker would have to supply their own recipes to make crimson slimeballs/blocks compatible with any other mod/item whose recipe uses slimes

I simply didnt want to provide recipes which a modpack *may* override

yes tags have a replace:false. but recipes do not

**Comment by CrimsonFluff** [comment]
dude, calm down

**Comment by CrimsonFluff** [comment]
you are only the 2nd person to ask for this, out of however many downloads. I thought it simple enough for mod pack makers to do the recipe stuff, as most packs have recipe changes

like I say... Im really not trying to be rude

**Comment by Skylortrexler** [comment]
> my thinking is that as there is no common slime ball tag (for fabric) , the mod pack maker would have to supply their own recipes to make crimson slimeballs/blocks compatible with any other mod/item whose recipe uses slimes

We are talking about VANILLA recipes dude. You refuse to add support for the base game.

**Comment by Skylortrexler** [comment]
I'm telling you, as someone who just hit 1,000,000 downloads the other day, you have to _try_ to make your mods work with stuff. Telling people to do it themselves will just make them say "nah" and remove the mod.

**Comment by Skylortrexler** [comment]
You are free to ignore my advice, but someone will just come along, fork your code, fix it and put it up and get the glory.

**Comment by CrimsonFluff** [comment]
like you are planning to do?  I could also say the same - as a modpack maker you too could add the recipes just as easy as i could

but I do see your point

**Comment by CrimsonFluff** [comment]
are we good, you going to let me make changes, now I see your valid point ?

**Comment by Skylortrexler** [comment]
> are we good, you going to let me make changes, now I see your valid point ?

No need, just submitted my Jar file to Curseforge with the changes. Currently adding config settings and more crafting recipes to it now.

**Comment by CrimsonFluff** [comment]
that was a bit extreme, I was willing to make the changes

**Comment by Skylortrexler** [comment]
Look, someone asked and you said no, I asked and you said no. So what was I supposed to do? You even told me to do it myself.

**Comment by CrimsonFluff** [comment]
I said you could do it as easy as me, I even said I see your point, for vanilla the changes make sense

to go from adding recipe yourself to taking my mod, come on

I never said at all said no (well not to you)  I just wanted you see my reasoning for not doing it

**Comment by CrimsonFluff** [comment]
what was you supposed to do?

make a pr request
add the recipes via datapacks/another mod

but im just nit picking

**Comment by Skylortrexler** [comment]
And why would I do the work for someone so ungrateful to take all the credit? Get bent.

**Comment by CrimsonFluff** [comment]
at no point was i being rude, or I didnt mean to convey rudeness

If I didnt care I wouldnt be here talking

**Comment by CrimsonFluff** [comment]
You asked what you could do, I was just offering suggestions

If you did offer help of course I can add you to the project, thats no problem

Im not having a go at you, again I even say I agree to making changes
